name: translation-env
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - brotlicffi=1.1.0.0=py311hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=hf384b4a_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.20.0=py311h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py311h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jinja2=3.1.6=py311h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.15.1.6=h2e68323_0
  - libcurand=10.4.0.35=h50d9014_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=2.1.1=py311h8fe796d_0
  - mkl_random=1.3.0=py311h505adc9_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.5=py311h06a4308_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py311h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_1
  - python=3.11.14=h6fa692b_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h591646f_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py311h06a4308_1
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - torchtriton=3.1.0=py311
  - typing_extensions=4.15.0=py311h06a4308_0
  - urllib3=2.5.0=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - babel==2.17.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.2.2
      - datasets==4.4.1
      - dill==0.4.0
      - docutils==0.21.2
      - flask==3.1.2
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==1.34.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.49.0rc1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - imagesize==1.4.1
      - indic-nlp-library-itt==0.1.1
      - indictranstoolkit==1.1.1
      - itsdangerous==2.2.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - markdown==3.10
      - matplotlib==3.10.7
      - morfessor==2.0.6
      - multidict==6.7.0
      - multiprocess==0.70.18
      - narwhals==2.12.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.12.0
      - platformdirs==4.5.0
      - portalocker==3.2.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.1.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - referencing==0.37.0
      - regex==2025.11.3
      - roman-numerals-py==3.1.0
      - rpds-py==0.29.0
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - sacremoses==0.1.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.46.0
      - seqeval==1.2.2
      - simpletransformers==0.70.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - sphinx==8.2.3
      - sphinx-argparse==0.5.2
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - streamlit==1.51.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - toml==0.10.2
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.45.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - wandb==0.23.0
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/manas/miniconda3/envs/translation-env
